### ISSUE TITLE
uploadimage function

### ISSUE THREAD

**Issue by heshamhanafyh95** [bastianraschke/pyfingerprint#35] opened 2018-03-14 00:03 UTC
i need uploadimage function can anyone help me

**Comment by philippmeisberger** [comment] 2018-03-14 08:50
Duplicate of #33

**Comment by phgachoud** [comment] 2018-04-15 03:25
can't you deal with characteristics strings instead??

**Comment by phgachoud** [comment] 2018-04-15 03:36
Did you take a look @ the documentation on page 8 point 4.1.1 https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/blob/master/documentation/ZFM-20_Fingerprint_Module.pdf and p.16-17

**Comment by bastianraschke** [comment] 2018-06-19 18:39
Because of no responses, i close the issue now.

**Closed as completed by bastianraschke** 2018-06-19 18:39 UTC
Labels: duplicate
