### ISSUE TITLE
pyfingerprint on Windows setup Issue

### ISSUE THREAD

**Issue by TehseenHasan** [bastianraschke/pyfingerprint#48] opened 2018-11-10 16:26 UTC
I was using pyfingerprint on Raspberry pi 3. It was great... working nice... Now I want to use same library on **Windows 10** (using Visual Studio or IDLE etc)... I have changes Port name from **/dev/ttyUSB0** to **COM5** as in Windows serial port name are in COM format.... But issue is that when I run the script (for example _example_downloadimage.py_) it show errors... 
1st error is that : `from pyfingerprint.pyfingerprint import PyFingerprint ImportError: No module named pyfingerprint`
I removed first pyfingerprint from pyfingerprint.pyfingerprint then this error gone..
Now it there is 2nd error  : **` The fingerprint sensor could not be initialized! The fingerprint sensor port COM5 was not found!`**
However I tried to make serial communication in a separate python file it works and there was no problem...

Another error also occurs saying: **`"name 'f' is not defined"`** 

This library does not integrating with Windows... Please help me on that issue...

**Comment by philippmeisberger** [comment] 2018-11-11 21:14
You are right! I created a fix for that.

**Comment by TehseenHasan** [comment] 2018-11-12 05:11
Thanks a lot ...

**Comment by TehseenHasan** [comment] 2018-11-12 05:34
All the example files are now working...I mainly working on 

> **example_downloadimage.py**

 file ... Now It is working.. But I have to remove pyfingerprint from : 

> **`from pyfingerprint.pyfingerprint import PyFingerprint`**

line and also comment out 

> **`exit(1)`**

 statement because it give some sort of exception errors... but after removing them... code is perfectly working...
New modified and working file is following:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PyFingerprint
Copyright (C) 2015 Bastian Raschke <bastian.raschke@posteo.de>
All rights reserved.

"""

import tempfile
from pyfingerprint import PyFingerprint


## Reads image and download it
##

## Tries to initialize the sensor
try:
    f = PyFingerprint('COM5', 115200, 0xFFFFFFFF, 0x00000000)

    if ( f.verifyPassword() == False ):
        raise ValueError('The given fingerprint sensor password is wrong!')

except Exception as e:
    print('The fingerprint sensor could not be initialized!')
    print('Exception message: ' + str(e))
    exit(1)

## Gets some sensor information
print('Currently used templates: ' + str(f.getTemplateCount()) +'/'+ str(f.getStorageCapacity()))

## Tries to read image and download it
try:
    print('Waiting for finger...')

    ## Wait that finger is read
    while ( f.readImage() == False ):
        pass

    print('Downloading image (this take a while)...')

    imageDestination =  tempfile.gettempdir() + '/fingerprint.bmp'
    print imageDestination
    f.downloadImage(imageDestination)

    print('The image was saved to "' + imageDestination + '".')

except Exception as e:
    print('Operation failed!')
    print('Exception message: ' + str(e))
    #exit(1)

```

**I want to download and save fingerprint Image in a folder. But getting this error...** 

![getimage](https://user-images.githubusercontent.com/25352528/48328460-e0a81f80-e665-11e8-8e24-3f3f8486bce2.JPG)

**Comment by philippmeisberger** [comment] 2018-11-12 09:16
> from pyfingerprint.pyfingerprint import PyFingerprint

will only work if you installed pyfingerprint package. To install it open command prompt in subfolder `src` and run `python setup.py install`.

I cannot reproduce the "image out of range" exception. Which Python version do you use? I use Python 3.7.1

**Comment by TehseenHasan** [comment] 2018-11-12 09:42
I'm using Python 2.7

**Comment by TehseenHasan** [comment] 2018-11-12 09:43
So what I should I do to avoid this "image out of range" exception???

**Comment by philippmeisberger** [comment] 2018-11-12 10:14
Never seen this exception. Ensure installing the package like I described. Revert all changes to the sample and try again. If this does not help try Python 3.

**Comment by TehseenHasan** [comment] 2018-11-12 10:23
I have installed using command Prompt as you described. But  
`from pyfingerprint.pyfingerprint import PyFingerprint` **`'No module named pyfingerprint'`** error again there... 

**`This is Command Prompt output:`**
```
python setup.py install

running install
running bdist_egg
running egg_info
creating files\pyfingerprint.egg-info
writing files\pyfingerprint.egg-info\PKG-INFO
writing top-level names to files\pyfingerprint.egg-info\top_level.txt
writing dependency_links to files\pyfingerprint.egg-info\dependency_links.txt
writing manifest file 'files\pyfingerprint.egg-info\SOURCES.txt'
reading manifest file 'files\pyfingerprint.egg-info\SOURCES.txt'
writing manifest file 'files\pyfingerprint.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\pyfingerprint
copying files\pyfingerprint\pyfingerprint.py -> build\lib\pyfingerprint
copying files\pyfingerprint\__init__.py -> build\lib\pyfingerprint
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pyfingerprint
copying build\lib\pyfingerprint\pyfingerprint.py -> build\bdist.win-amd64\egg\pyfingerprint
copying build\lib\pyfingerprint\__init__.py -> build\bdist.win-amd64\egg\pyfingerprint
byte-compiling build\bdist.win-amd64\egg\pyfingerprint\pyfingerprint.py to pyfingerprint.pyc
byte-compiling build\bdist.win-amd64\egg\pyfingerprint\__init__.py to __init__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying files\pyfingerprint.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying files\pyfingerprint.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying files\pyfingerprint.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying files\pyfingerprint.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\pyfingerprint-1.5-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pyfingerprint-1.5-py2.7.egg
Removing c:\python27amd64\lib\site-packages\pyfingerprint-1.5-py2.7.egg
Copying pyfingerprint-1.5-py2.7.egg to c:\python27amd64\lib\site-packages
pyfingerprint 1.5 is already the active version in easy-install.pth

Installed c:\python27amd64\lib\site-packages\pyfingerprint-1.5-py2.7.egg
Processing dependencies for pyfingerprint==1.5
Finished processing dependencies for pyfingerprint==1.5

```

**Comment by TehseenHasan** [comment] 2018-11-12 10:34
`'No module named pyfingerprint'` error is not an issue at this time... because it can be avoided after removing first `pyfingerprint ` from  
`from pyfingerprint.pyfingerprint import PyFingerprint` 
And code works without any error... Main issue is getting image from sensor... the **`"image out of range"`**  error...!!! 🙁

**Comment by philippmeisberger** [comment] 2018-11-12 10:36
Did you install `pillow` by using `pip install pillow`?

**Comment by TehseenHasan** [comment] 2018-11-12 11:27
Yes It was already installed.. command prompt shows this:

![pillow](https://user-images.githubusercontent.com/25352528/48344774-da329b80-e697-11e8-8918-cef6417d3790.JPG)

**Comment by philippmeisberger** [comment] 2018-11-12 11:42
Replace `exit(1)` by `raise e` inside last `except` block and paste the stack here

**Comment by TehseenHasan** [comment] 2018-11-12 18:39
In `example_downloadimage.py`  ,I replaced `exit(1)` with `raise e` .... Its output is like this: 

![imageindex](https://user-images.githubusercontent.com/25352528/48368520-c6a62580-e6d5-11e8-8fab-135d0035e1f3.JPG)

Image saves announcement and image index error are happening at same time...!!!  A `fingerprint.bmp`  file is created  on Desktop... But it is **corrupted** file:... And it looks like this : 


![fingerprint](https://user-images.githubusercontent.com/25352528/48368645-256b9f00-e6d6-11e8-9432-789d9cfa5de9.jpg)

**Comment by philippmeisberger** [comment] 2018-11-13 08:38
Which sensor do you use?

**Comment by TehseenHasan** [comment] 2018-11-13 08:52
Currently using **R305** Fingerprint Sensor... I was using same sensor with same library on Raspberry Pi 3 and working perfectly...  I have used **R301T** as well **FPM10A** Sensors with same setup on Raspberry Pi  3 using Python 2.7  and it was working perfect ....
![fpm10a](https://user-images.githubusercontent.com/25352528/48401468-12df7d00-e74b-11e8-80ee-bf9c086672ac.JPG)
![r305-fingerprint-800x800](https://user-images.githubusercontent.com/25352528/48401469-13781380-e74b-11e8-9a7f-bd87ed4b1d11.jpg)
![tb2an4jlhtlpufjsspfxxxlupxa_ 49207908](https://user-images.githubusercontent.com/25352528/48401471-13781380-e74b-11e8-94f5-46d4b7c517ed.jpg)

### **I have Tested _pyfingerprint_ on these three sensors on Raspberry Pi 3 with Python 2.7...Found No Problem**

**Comment by TehseenHasan** [comment] 2018-11-13 10:03
Now I'm checking **R301T** sensor on Windows using Visual Studio with exactly same setup same code  and this sensor **is working without errors**.  It is successfully saving fingerprint image on the given destination... While exactly same code is giving errors for R305 sensor...

This is the fingerprint.bmp generated by R301T sensor using same pyfingerprint code:
![fingerprint](https://user-images.githubusercontent.com/25352528/48405785-cbf68500-e754-11e8-9b14-68b23f54fa17.jpg)


### **Important Point:** 
**This sensor R301T gives image of resolution 192x192 pixel with 508 DPI.... 
While R305 Sensor giving image of resolution 256x288 pixel with 500 DPI...**

So I think problem is somewhere in **`def downloadImage(self, imageDestination)`** function in  **`pyfingerprint.py`** library file where it downloads image data from sensor image buffer.

**Comment by philippmeisberger** [comment] 2018-11-13 17:47
Sounds great that R301T works. I am wondering why R305 with same library version on Linux works but not on Windows. Could you please verify this again on Linux?

**Comment by philippmeisberger** [comment] 2018-11-13 18:17
Please also test changing image dimensions in following line to e.g. `(500, 500)`
https://github.com/bastianraschke/pyfingerprint/blob/a9356ee80cb7e04278e0a64186fc7c807de73242/src/files/pyfingerprint/pyfingerprint.py#L724

**Comment by TehseenHasan** [comment] 2018-11-13 19:41
> Please also test changing image dimensions in following line to e.g. `(500, 500)`
> [pyfingerprint/src/files/pyfingerprint/pyfingerprint.py](https://github.com/bastianraschke/pyfingerprint/blob/a9356ee80cb7e04278e0a64186fc7c807de73242/src/files/pyfingerprint/pyfingerprint.py#L724)
> 
> Line 724 in [a9356ee](/bastianraschke/pyfingerprint/commit/a9356ee80cb7e04278e0a64186fc7c807de73242)
> 
>  resultImage = Image.new('L', (256, 288), 'white')

Yes I tried this too...The results for R301T and R305 are as follows _**(On Windows 10 as well as Raspberry Pi 3 (Raspbian OS) Using Python 2.7 on both)**_ : 

### **Test Results for R301T Sensor:**
I changed those resolution parameters from `(256, 288)` up to `(2500, 2500)` different values... even `(10000, 10000)` ... each time sensor gives **correct image** with no error.... But for values **less than** `(256, 288)` it starts giving that error : `image index out of range` 
 even if I only lessened the resolution by 1 pixel e.g `(255, 287)` it starts giving error: `image index out of range` ... And if I place `raise e` in the last excaption  it again gives error but also generates corrupted image as shown below:
![fingerprint-1](https://user-images.githubusercontent.com/25352528/48435888-451aca00-e79f-11e8-9fe9-911bee59ce6a.jpg)

### **Test Results for R305 Sensor:**
On R305 Sensor I again changed the resolution parameters from `(256, 288)` up to `(1151, 1151)` different values... even I also tried smaller resolution than `(256, 288)` ... each time sensor gives Error: `image index out of range`  and corrupted image is formed ... And by gradually increasing the resolution I found that It start accepting resolution from **`(1152, 1152)`** to onward without giving error... error gone but **each time generated image is corrupted no matter what resolution I choose... !!!** 
Corrupted image is shown below: 
![fingerprint0](https://user-images.githubusercontent.com/25352528/48437827-397dd200-e7a4-11e8-9ba2-d5713c27ef16.jpg)


### **Conclusion:** 
I tested these two Sensors on both **Windows 10 and Raspberry Pi 3 on Python 2.7** on both ... Above 
 described results are **exactly same** for both platforms...
It means **Sensor R301T is working on both platforms**. While **Sensor R305 do not working at all on both platforms.**...

### **Important Point:**
This whole testing is done for getting image from sensor only... all the errors are only related to image getting from sensor.... while other functions of pyfingerprint like Enrolling, Delete template and searching are working successfully for both sensors....

**Comment by philippmeisberger** [comment] 2018-11-13 21:00
Thank you for your effort! Since the original issue with Windows seems to be fixed I vote for closing this issue and open a new one regarding that `downloadImage()` does not work correctly with R305.

**Comment by TehseenHasan** [comment] 2018-11-14 17:53
Okay what should do now.... Do you open new issue or I should open new issue ...?

**Comment by philippmeisberger** [comment] 2018-11-14 17:56
Feel free to open a new issue

**Closed as completed** 2018-11-14 18:37 UTC
Labels: bug

**Comment by Parixit1999** [comment] 2019-02-22 02:46
How I increase min accuracy score for the search in Database. Because I get "Not Match Found " error but user already in database.

**Comment by philippmeisberger** [comment] 2019-02-22 08:44
@Parixit1999 Please open a new issue with more details.

**Comment by ShinNics** [comment] 2019-09-27 01:17
Good day,

Can you tell me how you make your separate serial communication? I am stuck at your 2nd error where 
 The fingerprint sensor could not be initialized! The fingerprint sensor port COM5 was not found!
Thanks..

**Comment by TehseenHasan** [comment] 2019-09-27 19:01
> Good day,
> 
> Can you tell me how you make your separate serial communication? I am stuck at your 2nd error where
> The fingerprint sensor could not be initialized! The fingerprint sensor port COM5 was not found!
> Thanks..

I mean that I tried to communicate using COM5 in a simple Serial Communication program. For example I sent some characters to serial device (e.g. Arduino) attached to COM5. But when I connected the sensor at COM the library did not find the port... 
That issue was solved....
